dist: trusty
language: cpp
compiler: clang
before_install: sudo apt-get update
install: sudo apt-get install clang make automake libsdl2-dev libogg-dev libsdl2-image-dev libopenal-dev libvorbis-dev -y
script: cd source/src && make
notifications:
  irc:
    channels:
      - "underworld1.no.quakenet.org#assaultcube"
      - "underworld1.no.quakenet.org#assaultcube-dev"
    template:
      - "Build log for %{commit} by %{author}: %{build_url}"
    skip_join: true
